CREATE TABLE IF NOT EXISTS raw_businesses (
    id BIGSERIAL PRIMARY KEY,
    source TEXT,
    source_id TEXT,
    scraped_at TIMESTAMPTZ DEFAULT NOW(),
    raw_company_name TEXT,
    raw_address TEXT,
    raw_phone TEXT,
    raw_email TEXT,
    raw_website TEXT,
    raw_city TEXT,
    raw_state TEXT,
    raw_zip TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    raw_json JSONB
);

CREATE TABLE IF NOT EXISTS clean_businesses (
    business_id UUID PRIMARY KEY,
    canonical_name TEXT,
    alias_names TEXT[],
    industry_type TEXT,
    sub_industry TEXT,
    mailing_address TEXT,
    mailing_street TEXT,
    mailing_city TEXT,
    mailing_state TEXT,
    mailing_zip TEXT,
    physical_address TEXT,
    region TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    phone_primary TEXT,
    phone_secondary TEXT,
    email_primary TEXT,
    email_secondary TEXT,
    website TEXT,
    website_status TEXT,
    website_tech_stack JSONB,
    contact_form_url TEXT,
    facebook_url TEXT,
    facebook_followers INT,
    linkedin_url TEXT,
    linkedin_employee_count INT,
    google_reviews_rating NUMERIC,
    google_reviews_count INT,
    business_status TEXT,
    business_start_date DATE,
    registered_agent TEXT,
    entity_type TEXT,
    industry_attributes JSONB,
    data_completeness_score INT,
    authority_score INT,
    engagement_score INT,
    overall_lead_score INT,
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    enrichment_sources TEXT[]
);
